---
title: "Luxembourg Data"
format: pdf
editor: visual
echo: true
execute: 
  cache: true
toc: true
number-sections: true
---

## Luxembourg Data Project

git data alıp temizlicez

## Getting data

Take data from git

```{r libraries}
# Download raw Excel
library(readxl)
library(tidyverse)
library(janitor)

```

```{r}

url <- "https://github.com/b-rodrigues/rap4all/raw/master/datasets/vente-maison-2010-2021.xlsx"

# Shortened url

#url <- "https://is.gd/1vvBAc"

raw_data <- tempfile(fileext = ".xlsx")

download.file(url, raw_data, method = "auto", mode = "wb")

sheets <- excel_sheets(raw_data)

read_clean <- function(..., sheet){
  read_excel(..., sheet = sheet) |>
    mutate(year = sheet)
}

raw_data <- map(
  sheets,
  ~read_clean(raw_data,
              skip = 10,
              sheet = .)) |>
  bind_rows() |>
  clean_names()

```

See data

```{r}
raw_data
```

Translate to english

```{r}
raw_data <- raw_data |>
  rename(
    locality = commune,
    n_offers = nombre_doffres,
    average_price_nominal_euros = prix_moyen_annonce_en_courant,
    average_price_m2_nominal_euros = prix_moyen_annonce_au_m2_en_courant) |>
  mutate(locality = str_trim(locality)) |>
  select(year, locality, n_offers, starts_with("average"))

```

find bad entries

```{r}
raw_data |>
  filter(grepl('Luxembourg',locality)) %>% 
  count(locality)
raw_data %>% 
  filter(grepl('P.tange',locality)) %>% 
  count(locality)
```

## 
